### ISSUE TITLE
NPE on show report

### ISSUE THREAD

**Issue by tingsu** [koelleChristian/trickytripper#43]
The STR is: 

start the fresh app -> create a traveler (e.g., named "Ting") -> long press on the traveler "Ting" -> swipe from the tab "Travelers" to "Payments" -> click the menu option -> choose "Show report". The app crashes.

Stack Trace (the lines in the stack trace may be different, please reproduce to get the actual stack trace on your side, since I added some statements just for debugging):

java.lang.NullPointerException: Attempt to invoke virtual method 'void de.koelle.christian.trickytripper.TrickyTripperActivity.c(android.support.v7.view.b)' on a null object reference
        at de.koelle.christian.trickytripper.activities.a.a(ParticipantTabActivity.java:264)
        at de.koelle.christian.trickytripper.activities.a$b.a(ParticipantTabActivity.java:237)
        at android.support.v7.app.AppCompatDelegateImplV9$b.a(AppCompatDelegateImplV9.java:1795)
        at android.support.v7.app.q$a.c(WindowDecorActionBar.java:1007)
        at de.koelle.christian.trickytripper.activities.a$b.a(ParticipantTabActivity.java:200)
        at android.support.v7.app.AppCompatDelegateImplV9$b.a(AppCompatDelegateImplV9.java:1790)
        at android.support.v7.app.q$a.a(WindowDecorActionBar.java:1101)
        at android.support.v7.view.menu.h.a(MenuBuilder.java:817)
        at android.support.v7.view.menu.j.b(MenuItemImpl.java:156)
        at android.support.v7.view.menu.h.a(MenuBuilder.java:964)
        at android.support.v7.view.menu.m.onItemClick(MenuPopup.java:127)
        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
        at android.widget.AbsListView$3.run(AbsListView.java:3879)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Reproduced on the latest version 1.6.0 on Android 6.0 emulator.

**Comment by koelleChristian** [comment]
See https://github.com/koelleChristian/trickytripper/issues/42
